#!/usr/bin/env bash
# Install the widget as a launchable app on Linux (ChromeOS's Crostini
# container, or any XDG-compliant desktop) — no pip install involved, since a
# project with no dependencies has nothing for pip to resolve. This just
# points a launcher and an app-menu entry at the repo in place.
#
#     bash scripts/install_linux.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
BIN_DIR="$HOME/.local/bin"
APPS_DIR="$HOME/.local/share/applications"
ICON_DIR="$HOME/.local/share/icons"
LAUNCHER="$BIN_DIR/lagrange"
WIDGET_LAUNCHER="$BIN_DIR/lagrange-widget"
ICON_PATH="$ICON_DIR/lagrange.png"
DESKTOP_FILE="$APPS_DIR/lagrange.desktop"

command -v python3 >/dev/null || { echo "python3 not found" >&2; exit 1; }
python3 -c "import tkinter" 2>/dev/null || {
  echo "tkinter is missing — install it first: sudo apt install python3-tk" >&2
  exit 1
}

mkdir -p "$BIN_DIR" "$APPS_DIR" "$ICON_DIR"

python3 "$SCRIPT_DIR/make_icon_png.py" "$ICON_PATH" >/dev/null

cat > "$LAUNCHER" <<EOF
#!/bin/sh
# Generated by scripts/install_linux.sh — re-run it if this repo moves.
exec env PYTHONPATH="$REPO_DIR\${PYTHONPATH:+:\$PYTHONPATH}" python3 -m lagrange "\$@"
EOF
chmod +x "$LAUNCHER"

cat > "$WIDGET_LAUNCHER" <<EOF
#!/bin/sh
# Generated by scripts/install_linux.sh — re-run it if this repo moves.
exec env PYTHONPATH="$REPO_DIR\${PYTHONPATH:+:\$PYTHONPATH}" python3 -m lagrange widget "\$@"
EOF
chmod +x "$WIDGET_LAUNCHER"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Lagrange (Gemini Usage)
Comment=Live Gemini CLI (agy) quota and token usage widget
Exec=$LAUNCHER widget
Icon=$ICON_PATH
Terminal=false
Categories=Utility;Development;
StartupWMClass=lagrange-widget
EOF

echo "Installed:"
echo "  launcher   $LAUNCHER"
echo "  app entry  $DESKTOP_FILE"
echo "  icon       $ICON_PATH"
echo

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    echo "Note: $BIN_DIR is not on your PATH yet. Add this to ~/.bashrc, then"
    echo "open a new terminal:"
    echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo
    ;;
esac

echo 'Run it with "lagrange" (widget opens by default), or look for'
echo '"Lagrange (Gemini Usage)" in the ChromeOS app launcher — Crostini picks up'
echo 'the .desktop entry automatically, usually within a few seconds.'
